TimeKeeping/Controllers/DepartmentController.cs
using DAO;
using Entities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeKeeping.Common;

namespace TimeKeeping.Controllers
{
    public class DepartmentController : BaseController
    {
        // GET: Department
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var account_name = SessionHelper.getSession().userName;
            var empId = new AccountModel().GetEmployeeId(account_name);
            var emp = new EmployeeModel().GetEmployee(empId);
            ViewBag.FullName = emp.employee_first_name + " " + emp.employee_last_name;
            ViewBag.UserName = account_name;
            ViewBag.Posiion = emp.Position.position_name;
            ViewBag.Department = emp.Department.department_name;

            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var department = new DepartmentModel().FilterDepartment(sortOrder, searchString);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(department.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc, Department item)
        {
            item.department_name = fc["txtDepartmentName"];
            item.department_description = fc["txtDepartmentDescription"];
            var implDepartment = new DepartmentModel();
            try
            {
                implDepartment.InsertDepartment(item);
                TempData["msg"] = "<script>alert('Thêm mới thành công!');</script>";
            }
            catch
            {
                TempData["msg"] = "<script>alert('Thêm mới không thành công!');</script>";
            }
            return RedirectToAction("Index");
        }

        public ViewResult Update(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var account_name = SessionHelper.getSession().userName;
            var empId = new AccountModel().GetEmployeeId(account_name);
            var emp = new EmployeeModel().GetEmployee(empId);
            ViewBag.FullName = emp.employee_first_name + " " + emp.employee_last_name;
            ViewBag.UserName = account_name;
            ViewBag.Posiion = emp.Position.position_name;
            ViewBag.Department = emp.Department.department_name;

            var id = Int32.Parse(HttpContext.Request.QueryString["id"]);
            var department = new DepartmentModel().GetDepartment(id);
            ViewData["deptName"] = department.department_name;
            ViewData["deptDescription"] = department.department_description;
            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var dept = new DepartmentModel().FilterDepartment(sortOrder, searchString);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(dept.ToPagedList(pageNumber, pageSize));

        }

        [HttpPost]
        public ActionResult Update(FormCollection fc, Department item)
        {
            item.department_id = Int32.Parse(HttpContext.Request.QueryString["id"]);
            item.department_name = fc["txtDepartmentName"];
            item.department_description = fc["txtDepartmentDescription"];
            var implDepartment = new DepartmentModel();
            try
            {
                implDepartment.UpdateDepartment(item);
                TempData["msg"] = "<script>alert('Cập nhật thành công!');</script>";
            }
            catch
            {
                TempData["msg"] = "<script>alert('Cập nhật không thành công!');</script>";
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var implDepartment = new DepartmentModel();
            try
            {
                implDepartment.DeleteDepartment(id);
                TempData["msg"] = "<script>alert('Xóa thành công!');</script>";
            }
            catch
            {
                TempData["msg"] = "<script>alert('Xóa thất bại!');</script>";
            }
            return RedirectToAction("Index");
        }
    }
}

TimeKeeping/Views/Department/Index.cshtml
@model PagedList.IPagedList<Entities.Department>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section username{
    @Html.ViewBag.FullName (@Html.ViewBag.UserName)
}

@section nav{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li>
            <a href="/Home">
                <i class="fa fa-dashboard"></i> <span>Trang chủ</span>
            </a>
        </li>
        <li class="active">
            <a href="/Department">
                <i class="fa fa-dashboard"></i><span>Quản lý phòng ban</span>
            </a>
        </li>
        <li>
            <a href="/Position">
                <i class="fa fa-dashboard"></i><span>Quản lý chức vụ</span>
            </a>
        </li>
        <li>
            <a href="/Employee">
                <i class="fa fa-dashboard"></i> <span>Quản lý nhân viên</span>
            </a>
        </li>
        <li>
            <a href="/Office">
                <i class="fa fa-dashboard"></i><span>Quản lý văn phòng</span>
            </a>
        </li>
    </ul>
}

@section contentHeader{
    <h1>
        Quản lý phòng ban
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Home"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active"> Quản lý phòng ban</li>
    </ol>
}

<div class="row">
    <div class="col-md-5">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <h3 class="box-title">Thêm phòng ban</h3>
            </div>
            @using (Html.BeginForm())
            {
                <div class="box-body">
                    <div class="form-group">
                        <label for="departmentName">Tên phòng ban</label>
                        @Html.TextBox("txtDepartmentName", null, new { @type = "text", @class = "form-control", @placeholder = "Nhập tên phòng ban" })
                    </div>
                    <div class="form-group">
                        <label for="departmentDescription">Mô tả</label>
                        @Html.TextArea("txtDepartmentDescription", null, new { rows = "4", @type = "text", @class = "form-control", @placeholder = "Nhập tên mô tả" })
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Thêm</button>
                </div>
            }
            @Html.Raw(TempData["msg"])
        </div>
    </div>
    <div class="col-md-7">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <div class="col-sm-8">
                    <h3 class="box-title">Danh sách phòng ban</h3>
                </div>
                <div class="col-sm-4">
                    @using (Html.BeginForm("Index", "Department", FormMethod.Get))
                    {
                        <div class="input-group input-group">
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Nhập tên VP..." })
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    }
                </div>
            </div>
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <tr>
                        <th>ID</th>
                        <th>@Html.ActionLink("Tên phòng ban", "Index", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>Mô tả</th>
                        <th>Thao tác</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        using (Html.BeginForm("Delete", "Department", new { id = item.department_id }))
                        {
                            <tr>
                                <td>@item.department_id</td>
                                <td>@item.department_name</td>
                                <td>@item.department_description</td>
                                <td>
                                    <a class="btn btn-info" onclick="window.location.href='/Department/Update?id='+@item.department_id.ToString()">Sửa</a>
                                    <button type="submit" class="btn btn-default" onclick="return confirm('Bạn xác nhận xóa phòng @item.department_name?')">Xóa</button>
                                </td>
                            </tr>
                        }
                    }
                </table>
                <br />
                <div class="row">
                    <div class="col-sm-8">
                    </div>
                    <div class="col-sm-4">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TimeKeeping/Views/Department/Update.cshtml
@model PagedList.IPagedList<Entities.Department>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section username{
    @Html.ViewBag.FullName (@Html.ViewBag.UserName)
}

@section nav{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li>
            <a href="/Home">
                <i class="fa fa-dashboard"></i> <span>Trang chủ</span>
            </a>
        </li>
        <li class="active">
            <a href="/Department">
                <i class="fa fa-dashboard"></i><span>Quản lý phòng ban</span>
            </a>
        </li>
        <li>
            <a href="/Position">
                <i class="fa fa-dashboard"></i> <span>Quản lý chức vụ</span>
            </a>
        </li>
        <li>
            <a href="/Employee">
                <i class="fa fa-dashboard"></i> <span>Quản lý nhân viên</span>
            </a>
        </li>
        <li>
            <a href="/Office">
                <i class="fa fa-dashboard"></i><span>Quản lý văn phòng</span>
            </a>
        </li>
    </ul>
}

@section contentHeader{
    <h1>
        Quản lý phòng ban
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Home"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active"> Quản lý phòng ban</li>
    </ol>
}

<div class="row">
    <div class="col-md-5">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <h3 class="box-title">Cập nhật phòng ban</h3>
            </div>
            @using (Html.BeginForm())
            {
                <div class="box-body">
                    <div class="form-group">
                        <label for="departmentName">Tên phòng ban</label>
                        @Html.TextBox("txtDepartmentName", ViewData["deptName"], new { @type = "text", @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="departmentDescription">Mô tả</label>
                        @Html.TextArea("txtDepartmentDescription", new { rows = "4", @type = "text", @class = "form-control" })
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                    <button type="button" class="btn btn-default" onclick="history.go(-1); return false;">Trở về</button>
                </div>
            }
            @Html.Raw(TempData["msg"])
        </div>
    </div>
    <div class="col-md-7">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <div class="col-sm-8">
                    <h3 class="box-title">Danh sách phòng ban</h3>
                </div>
                <div class="col-sm-4">
                    @using (Html.BeginForm("Index", "Department", FormMethod.Get))
                    {
                        <div class="input-group input-group">
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Nhập tên VP..." })
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    }
                </div>
            </div>
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <tr>
                        <th>ID</th>
                        <th>@Html.ActionLink("Tên phòng ban", "Index", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>Mô tả</th>
                        <th>Thao tác</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        using (Html.BeginForm("Delete", "Department", new { id = item.department_id }))
                        {
                            <tr>
                                <td>@item.department_id</td>
                                <td>@item.department_name</td>
                                <td>@item.department_description</td>
                                <td>
                                    <a class="btn btn-info" onclick="window.location.href='/Department/Update?id='+@item.department_id.ToString()">Sửa</a>
                                    <button type="submit" class="btn btn-default" onclick="return confirm('Bạn xác nhận xóa phòng @item.department_name?')">Xóa</button>
                                </td>
                            </tr>
                        }
                    }
                </table>
                <br />
                <div class="row">
                    <div class="col-sm-8">
                    </div>
                    <div class="col-sm-4">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>