TimeKeeping/Controllers/PositionController.cs
using DAO;
using Entities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeKeeping.Common;

namespace TimeKeeping.Controllers
{
    public class PositionController : BaseController
    {
        // GET: Position
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var account_name = SessionHelper.getSession().userName;
            var empId = new AccountModel().GetEmployeeId(account_name);
            var emp = new EmployeeModel().GetEmployee(empId);
            ViewBag.FullName = emp.employee_first_name + " " + emp.employee_last_name;
            ViewBag.UserName = account_name;

            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var position = new PositionModel().FilterPosition(sortOrder, searchString);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(position.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc, Position item)
        {
            item.position_name = fc["txtPositionName"];
            item.salary = Int32.Parse(fc["txtSalary"]);
            var implPosition = new PositionModel();
            try
            {
                implPosition.InsertPosition(item);
                TempData["msg"] = "<script>alert('Thêm mới thành công!');</script>";
            }
            catch
            {
                TempData["msg"] = "<script>alert('Thêm mới không thành công!');</script>";
            }
            return RedirectToAction("Index");
        }

        public ViewResult Update(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var account_name = SessionHelper.getSession().userName;
            var empId = new AccountModel().GetEmployeeId(account_name);
            var emp = new EmployeeModel().GetEmployee(empId);
            ViewBag.FullName = emp.employee_first_name + " " + emp.employee_last_name;
            ViewBag.UserName = account_name;

            //var model = new PositionModel().GetAllPosition();
            var id = Int32.Parse(HttpContext.Request.QueryString["id"]);
            var pos = new PositionModel().GetPosition(id);
            ViewData["positionName"] = pos.position_name;
            ViewData["salary"] = pos.salary;

            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var item = new PositionModel().FilterPosition(sortOrder, searchString);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(item.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Update(FormCollection fc, Position item)
        {
            item.position_id = Int32.Parse(HttpContext.Request.QueryString["id"]);
            item.position_name = fc["txtPositionName"];
            item.salary = Int32.Parse(fc["txtSalary"]);
            var implPosition = new PositionModel();
            if (implPosition.UpdatePosition(item) != 1)
            {
                TempData["msg"] = "<script>alert('Cập nhật không thành công!');</script>";
            }
            TempData["msg"] = "<script>alert('Cập nhật thành công!');</script>";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var implPosition = new PositionModel();
            if (implPosition.DeletePosition(id) != 1)
            {
                TempData["msg"] = "<script>alert('Xóa thất bại!');</script>";
            }
            TempData["msg"] = "<script>alert('Xóa thành công!');</script>";
            return RedirectToAction("Index");
        }
    }
}

TimeKeeping/Views/Position/Index.cshtml
@model PagedList.IPagedList<Entities.Position>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section username{
    @Html.ViewBag.FullName (@Html.ViewBag.UserName)
}


@section nav{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li>
            <a href="/Home">
                <i class="fa fa-dashboard"></i> <span>Trang chủ</span>
            </a>
        </li>
        <li>
            <a href="/Department">
                <i class="fa fa-dashboard"></i><span>Quản lý phòng ban</span>
            </a>
        </li>
        <li class="active">
            <a href="/Position">
                <i class="fa fa-dashboard"></i><span>Quản lý chức vụ</span>
            </a>
        </li>
        <li>
            <a href="/Employee">
                <i class="fa fa-dashboard"></i> <span>Quản lý nhân viên</span>
            </a>
        </li>
        <li>
            <a href="/Office">
                <i class="fa fa-dashboard"></i><span>Quản lý văn phòng</span>
            </a>
        </li>
    </ul>
}

@section contentHeader{
    <h1>
        Quản lý chức vụ
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Home"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active"> Quản lý chức vụ</li>
    </ol>
}

<div class="row">
    <div class="col-md-5">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <h3 class="box-title">Thêm chức vụ</h3>
            </div>
            @using (Html.BeginForm())
            {
                <div class="box-body">
                    <div class="form-group">
                        <label for="positionName">Tên chức vụ</label>
                        @Html.TextBox("txtPositionName", null, new { @type = "text", @class = "form-control", @placeholder = "Nhập chức vụ" })
                    </div>
                    <div class="form-group">
                        <label for="salary">Lương theo chức vụ</label>
                        @Html.TextBox("txtSalary", null, new { @type = "text", @class = "form-control", @placeholder = "Nhập lương chức vụ" })
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Thêm</button>
                </div>
            }
            @Html.Raw(TempData["msg"])
        </div>
    </div>
    <div class="col-md-7">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <div class="col-sm-8">
                    <h3 class="box-title">Danh sách chức vụ</h3>
                </div>
                <div class="col-sm-4">
                    @using (Html.BeginForm("Index", "Position", FormMethod.Get))
                    {
                        <div class="input-group input-group">
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Nhập tên chức vụ..." })
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    }
                </div>
            </div>
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <tr>
                        <th>ID</th>
                        <th>@Html.ActionLink("Chức vụ", "Index", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>Lương</th>
                        <th>Thao tác</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        using (Html.BeginForm("Delete", "Position", new { id = item.position_id }))
                        {
                            <tr>
                                <td>@item.position_id</td>
                                <td>@item.position_name</td>
                                <td>@item.salary</td>
                                <td>
                                    <a class="btn btn-info" onclick="window.location.href='/Position/Update?id='+@item.position_id.ToString()">Sửa</a>
                                    <button type="submit" class="btn btn-default" onclick="return confirm('Bạn xác nhận xóa chức vụ @item.position_name?')">Xóa</button>
                                </td>
                            </tr>
                        }
                    }
                </table>
                <br />
                <div class="row">
                    <div class="col-sm-10">
                    </div>
                    <div class="col-sm-2">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TimeKeeping/Views/Position/Update.cshtml
@model PagedList.IPagedList<Entities.Position>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section username{
    @Html.ViewBag.FullName (@Html.ViewBag.UserName)
}


@section nav{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li>
            <a href="/Home">
                <i class="fa fa-dashboard"></i> <span>Trang chủ</span>
            </a>
        </li>
        <li>
            <a href="/Department">
                <i class="fa fa-dashboard"></i><span>Quản lý phòng ban</span>
            </a>
        </li>
        <li class="active">
            <a href="/Position">
                <i class="fa fa-dashboard"></i> <span>Quản lý chức vụ</span>
            </a>
        </li>
        <li>
            <a href="/Employee">
                <i class="fa fa-dashboard"></i> <span>Quản lý nhân viên</span>
            </a>
        </li>
        <li>
            <a href="/Office">
                <i class="fa fa-dashboard"></i><span>Quản lý văn phòng</span>
            </a>
        </li>
    </ul>
}

@section contentHeader{
    <h1>
        Quản lý chức vụ
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Home"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active"> Quản lý chức vụ</li>
    </ol>
}

<div class="row">
    <div class="col-md-5">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <h3 class="box-title">Cập nhật chức vụ</h3>
            </div>
            @using (Html.BeginForm())
            {
                <div class="box-body">
                    <div class="form-group">
                        <label for="positionName">Tên chức vụ</label>
                        @Html.TextBox("txtPositionName", ViewData["positionName"], new { @type = "text", @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label for="departmentDescription">Mô tả</label>
                        @Html.TextBox("txtSalary", ViewData["salary"], new { @type = "text", @class = "form-control" })
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                    <button type="button" class="btn btn-default" onclick="history.go(-1); return false;">Trở về</button>
                </div>
            }
            @Html.Raw(TempData["msg"])
        </div>
    </div>
    <div class="col-md-7">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <div class="col-sm-8">
                    <h3 class="box-title">Danh sách chức vụ</h3>
                </div>
                <div class="col-sm-4">
                    @using (Html.BeginForm("Index", "Position", FormMethod.Get))
                    {
                        <div class="input-group input-group">
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Nhập tên chức vụ..." })
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    }
                </div>
            </div>
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <tr>
                        <th>ID</th>
                        <th>@Html.ActionLink("Chức vụ", "Index", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>Lương</th>
                        <th>Thao tác</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        using (Html.BeginForm("Delete", "Position", new { id = item.position_id }))
                        {
                            <tr>
                                <td>@item.position_id</td>
                                <td>@item.position_name</td>
                                <td>@item.salary</td>
                                <td>
                                    <a class="btn btn-info" onclick="window.location.href='/Position/Update?id='+@item.position_id.ToString()">Sửa</a>
                                    <button type="submit" class="btn btn-default" onclick="return confirm('Bạn xác nhận xóa chức vụ @item.position_name?')">Xóa</button>
                                </td>
                            </tr>
                        }
                    }
                </table>
                <br />
                <div class="row">
                    <div class="col-sm-8">
                    </div>
                    <div class="col-sm-4">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>