TimeKeeping/Controllers/OfficeController.cs
using DAO;
using Entities;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeKeeping.Common;

namespace TimeKeeping.Controllers
{
    public class OfficeController : BaseController
    {
        // GET: Office
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var account_name = SessionHelper.getSession().userName;
            var empId = new AccountModel().GetEmployeeId(account_name);
            var emp = new EmployeeModel().GetEmployee(empId);
            ViewBag.FullName = emp.employee_first_name + " " + emp.employee_last_name;
            ViewBag.UserName = account_name;

            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var office = new OfficeModel().FilterOffice(sortOrder, searchString);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(office.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Index(FormCollection fc, Office off, Wifi wf)
        {
            wf.wifi_name = fc["txtWifiName"];
            wf.wifi_ip = fc["txtWifiIp"];
            try
            {
                var id = new WifiModel().InsertWifi(wf);
                if (id != 0)
                {
                    off.office_name = fc["txtOfficeName"];
                    off.wifi_id = id;
                    off.office_id = 1;
                    var implOffice = new OfficeModel();
                    try
                    {
                        implOffice.InsertOffice(off);
                        TempData["msg"] = "<script>alert('Thêm mới thành công!');</script>";
                    }
                    catch
                    {
                        TempData["msg"] = "<script>alert('Thêm mới không thành công!');</script>";
                    }
                }
                else
                {
                    TempData["msg"] = "<script>alert('Thêm mới không thành công!');</script>";
                }
            }
            catch
            {
                TempData["msg"] = "<script>alert('Thêm mới không thành công! Wifi đã tồn tại!');</script>";
            }

            return RedirectToAction("Index");
        }

        public ViewResult Update(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var account_name = SessionHelper.getSession().userName;
            var empId = new AccountModel().GetEmployeeId(account_name);
            var emp = new EmployeeModel().GetEmployee(empId);
            ViewBag.FullName = emp.employee_first_name + " " + emp.employee_last_name;
            ViewBag.UserName = account_name;

            //var model = new OfficeModel().GetAllOffice();
            var id = Int32.Parse(HttpContext.Request.QueryString["id"]);
            var office = new OfficeModel().GetOffice(id);
            ViewData["officeName"] = office.office_name;
            ViewData["wifiName"] = office.Wifi.wifi_name;
            ViewData["wifiIp"] = office.Wifi.wifi_ip;

            ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var off = new OfficeModel().FilterOffice(sortOrder, searchString);

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(off.ToPagedList(pageNumber, pageSize));
        }

        [HttpPost]
        public ActionResult Update(FormCollection fc, Office item)
        {
            var implOffice = new OfficeModel();
            var implWifi = new WifiModel();
            item.office_id = Int32.Parse(HttpContext.Request.QueryString["id"]);
            item.office_name = fc["txtOfficeName"];
            item.wifi_id = implOffice.GetWifiId(Int32.Parse(HttpContext.Request.QueryString["id"]));
            var inputWifi = new Wifi()
            {
                wifi_id = (int)item.wifi_id,
                wifi_name = fc["txtwifiName"],
                wifi_ip = fc["txtWifiIp"]
            };
            if (!implWifi.isExists(inputWifi))
            {
                try
                {
                    item.wifi_id = implWifi.InsertWifi(inputWifi);
                }
                catch
                {
                    implWifi.UpdateWifi(inputWifi);
                }
            }
            implOffice.UpdateOffice(item);
            TempData["msg"] = "<script>alert('Cập nhật thành công!');</script>";
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var implOffice = new OfficeModel();
            var off = implOffice.GetOffice(id);
            try
            {
                implOffice.DeleteOffice(id);
                new WifiModel().DeleteWifi((int)off.wifi_id);
                TempData["msg"] = "<script>alert('Xóa thành công!');</script>";
            }
            catch
            {
                TempData["msg"] = "<script>alert('Xóa thất bại!');</script>";
            }
            return RedirectToAction("Index");
        }
    }
}

TimeKeeping/Views/Office/Index.cshtml
@model PagedList.IPagedList<Entities.Office>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section username{
    @Html.ViewBag.FullName (@Html.ViewBag.UserName)
}

@section nav{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li>
            <a href="/Home">
                <i class="fa fa-dashboard"></i> <span>Trang chủ</span>
            </a>
        </li>
        <li>
            <a href="/Department">
                <i class="fa fa-dashboard"></i><span>Quản lý phòng ban</span>
            </a>
        </li>
        <li>
            <a href="/Position">
                <i class="fa fa-dashboard"></i><span>Quản lý chức vụ</span>
            </a>
        </li>
        <li>
            <a href="/Employee">
                <i class="fa fa-dashboard"></i> <span>Quản lý Nhân viên</span>
            </a>
        </li>
        <li class="active">
            <a href="/Office">
                <i class="fa fa-dashboard"></i><span>Quản lý văn phòng</span>
            </a>
        </li>
    </ul>
}

@section contentHeader{
    <h1>
        Quản lý văn phòng
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Home"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active"> Quản lý văn phòng</li>
    </ol>
}

<div class="row">
    <div class="col-md-5">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <h3 class="box-title">Thêm văn phòng</h3>
            </div>
            @using (Html.BeginForm())
            {
                <div class="box-body">
                    <div class="form-group">
                        <label for="departmentName">Tên văn phòng</label>
                        @Html.TextBox("txtOfficeName", null, new { @type = "text", @class = "form-control", @placeholder = "Tên văn phòng" })
                    </div>
                    <div class="form-group">
                        <label for="wifiId">IP Wifi</label>
                        @Html.TextBox("txtWifiIp", null, new { rows = "4", @type = "text", @class = "form-control", @placeholder = "Địa chỉ wifi" })
                    </div>
                    <div class="form-group">
                        <label for="wifiName">Tên Wifi</label>
                        @Html.TextBox("txtWifiName", null, new { rows = "4", @type = "text", @class = "form-control", @placeholder = "Tên wifi" })
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Thêm</button>
                </div>
            }
            @Html.Raw(TempData["msg"])
        </div>
    </div>
    <div class="col-md-7">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <div class="col-sm-8">
                    <h3 class="box-title">Danh sách văp phòng</h3>
                </div>
                <div class="col-sm-4">
                    @using (Html.BeginForm("Index", "Office", FormMethod.Get))
                    {
                        <div class="input-group input-group">
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Nhập tên VP..." })
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    }
                </div>
            </div>
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <tr>
                        <th>ID</th>
                        <th>@Html.ActionLink("Văn phòng", "Index", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>Wifi</th>
                        <th>IP</th>
                        <th>Thao tác</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        using (Html.BeginForm("Delete", "Office", new { id = item.office_id }))
                        {
                            <tr>
                                <td>@item.office_id</td>
                                <td>@item.office_name</td>
                                <td>@item.Wifi.wifi_name</td>
                                <td>@item.Wifi.wifi_ip</td>
                                <td>
                                    <a class="btn btn-info" onclick="window.location.href='/Office/Update?id='+@item.office_id.ToString()">Sửa</a>
                                    <button type="submit" class="btn btn-default" onclick="return confirm('Bạn xác nhận xóa văn phòng @item.office_name?')">Xóa</button>
                                </td>
                            </tr>
                        }
                    }
                </table>
                <br />
                <div class="row">
                    <div class="col-sm-8">
                    </div>
                    <div class="col-sm-4">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

TimeKeeping/Views/Office/Update.cshtml
@model PagedList.IPagedList<Entities.Office>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section username{
    @Html.ViewBag.FullName (@Html.ViewBag.UserName)
}


@section nav{
    <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li>
            <a href="/Home">
                <i class="fa fa-dashboard"></i> <span>Trang chủ</span>
            </a>
        </li>
        <li>
            <a href="/Department">
                <i class="fa fa-dashboard"></i><span>Quản lý phòng ban</span>
            </a>
        </li>
        <li>
            <a href="/Position">
                <i class="fa fa-dashboard"></i><span>Quản lý chức vụ</span>
            </a>
        </li>
        <li>
            <a href="/Employee">
                <i class="fa fa-dashboard"></i> <span>Quản lý Nhân viên</span>
            </a>
        </li>
        <li class="active">
            <a href="/Office">
                <i class="fa fa-dashboard"></i><span>Quản lý văn phòng</span>
            </a>
        </li>
    </ul>
}

@section contentHeader{
    <h1>
        Quản lý văn phòng
    </h1>
    <ol class="breadcrumb">
        <li><a href="/Home"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
        <li class="active"> Quản lý văn phòng</li>
    </ol>
}

<div class="row">
    <div class="col-md-5">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <h3 class="box-title">Cập nhật văn phòng</h3>
            </div>
            @using (Html.BeginForm())
            {
                <div class="box-body">
                    <div class="form-group">
                        <label for="departmentName">Tên văn phòng</label>
                        @Html.TextBox("txtOfficeName", ViewData["officeName"], new { @type = "text", @class = "form-control", @placeholder = "Tên văn phòng" })
                    </div>
                    <div class="form-group">
                        <label for="wifiId">IP Wifi</label>
                        @Html.TextBox("txtWifiIp", ViewData["wifiIp"], new { rows = "4", @type = "text", @class = "form-control", @placeholder = "Địa chỉ wifi" })
                    </div>
                    <div class="form-group">
                        <label for="wifiName">Tên Wifi</label>
                        @Html.TextBox("txtWifiName", ViewData["wifiName"], new { rows = "4", @type = "text", @class = "form-control", @placeholder = "Tên wifi" })
                    </div>
                </div>
                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Cập nhật</button>
                    <button type="button" class="btn btn-default" onclick="history.go(-1); return false;">Trở về</button>
                </div>
            }
            @Html.Raw(TempData["msg"])
        </div>
    </div>
    <div class="col-md-7">
        <div class="box box-info">
            <br />
            <div class="box-header">
                <div class="col-sm-8">
                    <h3 class="box-title">Danh sách văp phòng</h3>
                </div>
                <div class="col-sm-4">
                    @using (Html.BeginForm("Index", "Office", FormMethod.Get))
                    {
                        <div class="input-group input-group">
                            @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Nhập tên VP..." })
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-info btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    }
                </div>
            </div>
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover">
                    <tr>
                        <th>ID</th>
                        <th>@Html.ActionLink("Văn phòng", "Index", new { sortOrder = ViewBag.NameSortParam, currentFilter = ViewBag.CurrentFilter })</th>
                        <th>Wifi</th>
                        <th>IP</th>
                        <th>Thao tác</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        using (Html.BeginForm("Delete", "Office", new { id = item.office_id }))
                        {
                            <tr>
                                <td>@item.office_id</td>
                                <td>@item.office_name</td>
                                <td>@item.Wifi.wifi_name</td>
                                <td>@item.Wifi.wifi_ip</td>
                                <td>
                                    <a class="btn btn-info" onclick="window.location.href='/Office/Update?id='+@item.office_id.ToString()">Sửa</a>
                                    <button type="submit" class="btn btn-default" onclick="return confirm('Bạn xác nhận xóa văn phòng @item.office_name?')">Xóa</button>
                                </td>
                            </tr>
                        }
                    }
                </table>
                <br />
                <div class="row">
                    <div class="col-sm-8">
                    </div>
                    <div class="col-sm-4">
                        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>